### PR TITLE
Merge with main, fixing merge conflicts

### PR DESCRIPTION
**Pull request by nyurik**

### CODE REVIEW

**Comment by m4b** [comment]
i don't really understand what's going on in this PR, but @Frostie314159 's PR should simply be rebased on master (sorry for the merge conflicts, but alas this is life); each commit should apply cleanly, ideally no merge commits, etc.

With @nyurik 's last two PR's there shouldn't be any merge conflicts anymore (it's possible the fmt string one will, but hard to say).

**Comment by m4b** [comment]
I realized this is frostie's forked repo after i wrote this, but i think still the same solution should be applied, something like (feel free to correct, but this is the general gist of what i'd do, also i haven't added an upstream remote in a while so that syntax could be wrong):

```
git remote add upstream https://github.com/m4b/scroll
git checkout upstream/master
git pull
git checkout my_branch
git rebase upstream/master
# fix merge conflicts
git push --force
```

**Comment by nyurik** [comment]
@m4b it is easier to do a merge than to rebase.  This PR fixes the merge conflict.  Afterwards, you can "squash merge" - which keeps your git history linear and simple, combining all changes into one simple commit.

**Comment by nyurik** [comment]
in other words, this PR contains all the changes that were happening on the main branch, plus the merge fix.  Once it is merged, you will have a clean diff with whatever is on the main branch, and you can squash merge.

**Comment by m4b** [comment]
ok sounds good

**Pull request merged**
